/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import LinhaDeCodigo.ToDoList;
import javax.swing.JOptionPane;

/**
 *
 * @author SESI_SENAI
 */
public class TelaDeCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeCadastro
     */
    public TelaDeCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        BotaoDeCadastro = new javax.swing.JButton();
        BotaoDeSair = new javax.swing.JButton();
        NomeDoUsuario = new javax.swing.JTextField();
        IdadeDoUsuario = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(195, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tela de Cadastro", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        BotaoDeCadastro.setText("Cadastrar");
        BotaoDeCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoDeCadastroActionPerformed(evt);
            }
        });

        BotaoDeSair.setText("Sair");
        BotaoDeSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoDeSairActionPerformed(evt);
            }
        });

        NomeDoUsuario.setBackground(new java.awt.Color(204, 204, 255));
        NomeDoUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nome Completo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        NomeDoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeDoUsuarioActionPerformed(evt);
            }
        });

        IdadeDoUsuario.setBackground(new java.awt.Color(204, 204, 255));
        IdadeDoUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Idade"));
        IdadeDoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdadeDoUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotaoDeCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotaoDeSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(NomeDoUsuario)
                    .addComponent(IdadeDoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(NomeDoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(IdadeDoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotaoDeCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoDeSair)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomeDoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeDoUsuarioActionPerformed

    }//GEN-LAST:event_NomeDoUsuarioActionPerformed

    private void BotaoDeSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoDeSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotaoDeSairActionPerformed

    private void IdadeDoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdadeDoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdadeDoUsuarioActionPerformed

    private void BotaoDeCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoDeCadastroActionPerformed

        if (NomeDoUsuario.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO PREENCHEU O BLOCO ''NOME COMPLETO''!!");
            
        }else if (IdadeDoUsuario.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "VOCÊ NÃO PREENCHEU O BLOCO ''IDADE''!!");
                
        } else {
            ToDoList.login.setVisible(false);
            ToDoList.home = new TelaPrincipal();
            ToDoList.home.setVisible(true);
        
        }
    }//GEN-LAST:event_BotaoDeCadastroActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoDeCadastro;
    private javax.swing.JButton BotaoDeSair;
    private javax.swing.JTextField IdadeDoUsuario;
    private javax.swing.JTextField NomeDoUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
