/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author SESI_SENAI
 */
public class TelaPrincipal extends javax.swing.JFrame {

    public static int QuantidadeTarefas = 0;
    public static int indice = 1;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        InserirTarefa = new javax.swing.JTextField();
        BotaoDeAdicionar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Check1 = new javax.swing.JLabel();
        Check2 = new javax.swing.JLabel();
        Check3 = new javax.swing.JLabel();
        Check4 = new javax.swing.JLabel();
        Check5 = new javax.swing.JLabel();
        Check6 = new javax.swing.JLabel();
        Check7 = new javax.swing.JLabel();
        Check8 = new javax.swing.JLabel();
        Check9 = new javax.swing.JLabel();
        Check10 = new javax.swing.JLabel();
        Falha1 = new javax.swing.JLabel();
        Falha2 = new javax.swing.JLabel();
        Falha3 = new javax.swing.JLabel();
        Falha4 = new javax.swing.JLabel();
        Falha5 = new javax.swing.JLabel();
        Falha6 = new javax.swing.JLabel();
        Falha7 = new javax.swing.JLabel();
        Falha8 = new javax.swing.JLabel();
        Falha9 = new javax.swing.JLabel();
        Falha10 = new javax.swing.JLabel();
        Edit1 = new javax.swing.JLabel();
        Edit2 = new javax.swing.JLabel();
        Edit3 = new javax.swing.JLabel();
        Edit4 = new javax.swing.JLabel();
        Edit5 = new javax.swing.JLabel();
        Edit6 = new javax.swing.JLabel();
        Edit7 = new javax.swing.JLabel();
        Edit8 = new javax.swing.JLabel();
        Edit9 = new javax.swing.JLabel();
        Edit10 = new javax.swing.JLabel();
        Tarefa1 = new javax.swing.JTextField();
        Tarefa2 = new javax.swing.JTextField();
        Tarefa3 = new javax.swing.JTextField();
        Tarefa4 = new javax.swing.JTextField();
        Tarefa5 = new javax.swing.JTextField();
        Tarefa6 = new javax.swing.JTextField();
        Tarefa7 = new javax.swing.JTextField();
        Tarefa8 = new javax.swing.JTextField();
        Tarefa9 = new javax.swing.JTextField();
        Tarefa10 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(195, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        InserirTarefa.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        InserirTarefa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        InserirTarefa.setText("Nova Tarefa");
        InserirTarefa.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BotaoDeAdicionar.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        BotaoDeAdicionar.setText("+");
        BotaoDeAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoDeAdicionarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Área de Tarefas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(51, 255, 51));

        Check1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/check-icone-6.png"))); // NOI18N
        Check1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Check1MouseClicked(evt);
            }
        });

        Check2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/check-icone-6.png"))); // NOI18N
        Check2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Check2MouseClicked(evt);
            }
        });

        Check3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/check-icone-6.png"))); // NOI18N
        Check3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Check3MouseClicked(evt);
            }
        });

        Check4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/check-icone-6.png"))); // NOI18N
        Check4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Check4MouseClicked(evt);
            }
        });

        Check5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/check-icone-6.png"))); // NOI18N
        Check5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Check5MouseClicked(evt);
            }
        });

        Check6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/check-icone-6.png"))); // NOI18N
        Check6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Check6MouseClicked(evt);
            }
        });

        Check7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/check-icone-6.png"))); // NOI18N
        Check7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Check7MouseClicked(evt);
            }
        });

        Check8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/check-icone-6.png"))); // NOI18N
        Check8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Check8MouseClicked(evt);
            }
        });

        Check9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/check-icone-6.png"))); // NOI18N
        Check9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Check9MouseClicked(evt);
            }
        });

        Check10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/check-icone-6.png"))); // NOI18N
        Check10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Check10MouseClicked(evt);
            }
        });

        Falha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/pngaaauuuu.png"))); // NOI18N
        Falha1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Falha1MouseClicked(evt);
            }
        });

        Falha2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/pngaaauuuu.png"))); // NOI18N
        Falha2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Falha2MouseClicked(evt);
            }
        });

        Falha3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/pngaaauuuu.png"))); // NOI18N
        Falha3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Falha3MouseClicked(evt);
            }
        });

        Falha4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/pngaaauuuu.png"))); // NOI18N
        Falha4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Falha4MouseClicked(evt);
            }
        });

        Falha5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/pngaaauuuu.png"))); // NOI18N
        Falha5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Falha5MouseClicked(evt);
            }
        });

        Falha6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/pngaaauuuu.png"))); // NOI18N
        Falha6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Falha6MouseClicked(evt);
            }
        });

        Falha7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/pngaaauuuu.png"))); // NOI18N
        Falha7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Falha7MouseClicked(evt);
            }
        });

        Falha8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/pngaaauuuu.png"))); // NOI18N
        Falha8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Falha8MouseClicked(evt);
            }
        });

        Falha9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/pngaaauuuu.png"))); // NOI18N
        Falha9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Falha9MouseClicked(evt);
            }
        });

        Falha10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/pngaaauuuu.png"))); // NOI18N
        Falha10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Falha10MouseClicked(evt);
            }
        });

        Edit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/edit.png"))); // NOI18N
        Edit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Edit1MouseClicked(evt);
            }
        });

        Edit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/edit.png"))); // NOI18N
        Edit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Edit2MouseClicked(evt);
            }
        });

        Edit3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/edit.png"))); // NOI18N
        Edit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Edit3MouseClicked(evt);
            }
        });

        Edit4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/edit.png"))); // NOI18N
        Edit4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Edit4MouseClicked(evt);
            }
        });

        Edit5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/edit.png"))); // NOI18N
        Edit5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Edit5MouseClicked(evt);
            }
        });

        Edit6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/edit.png"))); // NOI18N
        Edit6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Edit6MouseClicked(evt);
            }
        });

        Edit7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/edit.png"))); // NOI18N
        Edit7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Edit7MouseClicked(evt);
            }
        });

        Edit8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/edit.png"))); // NOI18N
        Edit8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Edit8MouseClicked(evt);
            }
        });

        Edit9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/edit.png"))); // NOI18N
        Edit9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Edit9MouseClicked(evt);
            }
        });

        Edit10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/edit.png"))); // NOI18N
        Edit10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Edit10MouseClicked(evt);
            }
        });

        Tarefa1.setEditable(false);
        Tarefa1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Tarefa2.setEditable(false);
        Tarefa2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Tarefa3.setEditable(false);
        Tarefa3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Tarefa4.setEditable(false);
        Tarefa4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Tarefa5.setEditable(false);
        Tarefa5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Tarefa6.setEditable(false);
        Tarefa6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Tarefa7.setEditable(false);
        Tarefa7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Tarefa8.setEditable(false);
        Tarefa8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Tarefa9.setEditable(false);
        Tarefa9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Tarefa10.setEditable(false);
        Tarefa10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Tarefa9)
                    .addComponent(Tarefa10, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tarefa7)
                    .addComponent(Tarefa8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tarefa5)
                    .addComponent(Tarefa6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tarefa3)
                    .addComponent(Tarefa4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tarefa1)
                    .addComponent(Tarefa2, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Check1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Falha1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Edit1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(Check6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Falha6))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Check3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Falha3))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Check2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Falha2))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Check4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Falha4))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Check5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Falha5))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Check7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Falha7))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Check8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Falha8)))
                                .addGap(1, 1, 1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Edit2)
                            .addComponent(Edit3)
                            .addComponent(Edit4)
                            .addComponent(Edit5)
                            .addComponent(Edit6)
                            .addComponent(Edit7)
                            .addComponent(Edit8)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Check9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Falha9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Edit9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Check10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Falha10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Edit10)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tarefa1)
                            .addComponent(Check1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Falha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tarefa2)
                            .addComponent(Check2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Falha2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Edit2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Edit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(54, 54, 54)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tarefa3)
                    .addComponent(Check3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Falha3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Edit3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Check4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Tarefa4)
                            .addComponent(Falha4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tarefa5)
                            .addComponent(Falha5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Edit5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Check5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Edit4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(60, 60, 60)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Edit6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tarefa6)
                    .addComponent(Falha6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Check6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tarefa7)
                    .addComponent(Check7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Falha7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Edit7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Falha8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tarefa8)
                    .addComponent(Check8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Edit8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tarefa9)
                    .addComponent(Check9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Falha9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Edit9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tarefa10)
                    .addComponent(Check10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Falha10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Edit10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(InserirTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoDeAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(InserirTarefa)
                    .addComponent(BotaoDeAdicionar))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoDeAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoDeAdicionarActionPerformed

        if (QuantidadeTarefas < 10) {

            String texto = InserirTarefa.getText();
            
            adicionar(indice, texto);
            indice++;
            QuantidadeTarefas++;

        } else {
            JOptionPane.showMessageDialog(null, "VOCÊ CHEGOU NO LIMITE MÁXIMO DE TAREFAS");
        }

        InserirTarefa.setText("");
    }//GEN-LAST:event_BotaoDeAdicionarActionPerformed

    private void Check1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Check1MouseClicked
        Tarefa1.setBackground(new Color(82, 214, 116));
    }//GEN-LAST:event_Check1MouseClicked

    private void Check2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Check2MouseClicked
        Tarefa2.setBackground(new Color(82, 214, 116));
    }//GEN-LAST:event_Check2MouseClicked

    private void Check3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Check3MouseClicked
        Tarefa3.setBackground(new Color(82, 214, 116));
    }//GEN-LAST:event_Check3MouseClicked

    private void Check4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Check4MouseClicked
        Tarefa4.setBackground(new Color(82, 214, 116));
    }//GEN-LAST:event_Check4MouseClicked

    private void Check5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Check5MouseClicked
        Tarefa5.setBackground(new Color(82, 214, 116));
    }//GEN-LAST:event_Check5MouseClicked

    private void Check6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Check6MouseClicked
        Tarefa6.setBackground(new Color(82, 214, 116));
    }//GEN-LAST:event_Check6MouseClicked

    private void Check7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Check7MouseClicked
        Tarefa7.setBackground(new Color(82, 214, 116));
    }//GEN-LAST:event_Check7MouseClicked

    private void Check8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Check8MouseClicked
        Tarefa8.setBackground(new Color(82, 214, 116));
    }//GEN-LAST:event_Check8MouseClicked

    private void Falha2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Falha2MouseClicked
        Tarefa2.setBackground(Color.PINK);
    }//GEN-LAST:event_Falha2MouseClicked

    private void Falha3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Falha3MouseClicked
        Tarefa3.setBackground(Color.PINK);
    }//GEN-LAST:event_Falha3MouseClicked

    private void Falha4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Falha4MouseClicked
        Tarefa4.setBackground(Color.PINK);
    }//GEN-LAST:event_Falha4MouseClicked

    private void Falha6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Falha6MouseClicked
        Tarefa6.setBackground(Color.PINK);
    }//GEN-LAST:event_Falha6MouseClicked

    private void Falha5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Falha5MouseClicked
        Tarefa5.setBackground(Color.PINK);
    }//GEN-LAST:event_Falha5MouseClicked

    private void Falha7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Falha7MouseClicked
        Tarefa7.setBackground(Color.PINK);
    }//GEN-LAST:event_Falha7MouseClicked

    private void Falha8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Falha8MouseClicked
        Tarefa8.setBackground(Color.PINK);
    }//GEN-LAST:event_Falha8MouseClicked

    private void Edit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Edit1MouseClicked
        Tarefa1.setEditable(!Tarefa1.isEditable());
    }//GEN-LAST:event_Edit1MouseClicked

    private void Edit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Edit2MouseClicked
        Tarefa2.setEditable(!Tarefa2.isEditable());
    }//GEN-LAST:event_Edit2MouseClicked

    private void Edit3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Edit3MouseClicked
        Tarefa3.setEditable(!Tarefa3.isEditable());
    }//GEN-LAST:event_Edit3MouseClicked

    private void Edit4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Edit4MouseClicked
        Tarefa4.setEditable(!Tarefa4.isEditable());
    }//GEN-LAST:event_Edit4MouseClicked

    private void Edit5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Edit5MouseClicked
        Tarefa5.setEditable(!Tarefa5.isEditable());
    }//GEN-LAST:event_Edit5MouseClicked

    private void Edit6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Edit6MouseClicked
        Tarefa6.setEditable(!Tarefa6.isEditable());
    }//GEN-LAST:event_Edit6MouseClicked

    private void Edit7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Edit7MouseClicked
        Tarefa7.setEditable(!Tarefa7.isEditable());
    }//GEN-LAST:event_Edit7MouseClicked

    private void Edit8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Edit8MouseClicked
        Tarefa8.setEditable(!Tarefa8.isEditable());
    }//GEN-LAST:event_Edit8MouseClicked

    private void Check9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Check9MouseClicked
        Tarefa9.setBackground(new Color(82, 214, 116));
    }//GEN-LAST:event_Check9MouseClicked

    private void Check10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Check10MouseClicked
        Tarefa10.setBackground(new Color(82, 214, 116));
    }//GEN-LAST:event_Check10MouseClicked

    private void Falha9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Falha9MouseClicked
        Tarefa9.setBackground(Color.PINK);
    }//GEN-LAST:event_Falha9MouseClicked

    private void Falha10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Falha10MouseClicked
        Tarefa10.setBackground(Color.PINK);
    }//GEN-LAST:event_Falha10MouseClicked

    private void Edit9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Edit9MouseClicked
        Tarefa9.setEditable(!Tarefa9.isEditable());
    }//GEN-LAST:event_Edit9MouseClicked

    private void Edit10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Edit10MouseClicked
        Tarefa10.setEditable(!Tarefa10.isEditable());
    }//GEN-LAST:event_Edit10MouseClicked

    private void Falha1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Falha1MouseClicked
        Tarefa1.setBackground(Color.pink);
    }//GEN-LAST:event_Falha1MouseClicked

    public void adicionar(int posicao, String texto) {

        switch (posicao) {
            case 1:
                Tarefa1.setText(texto);
                break;
            case 2:
                Tarefa2.setText(texto);
                break;
            case 3:
                Tarefa3.setText(texto);
                break;
            case 4:
                Tarefa4.setText(texto);
                break;
            case 5:
                Tarefa5.setText(texto);
                break;
            case 6:
                Tarefa6.setText(texto);
                break;
            case 7:
                Tarefa7.setText(texto);
                break;
            case 8:
                Tarefa8.setText(texto);
                break;
            case 9:
                Tarefa9.setText(texto);
                break;
            case 10:
                Tarefa10.setText(texto);
                break;

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoDeAdicionar;
    private javax.swing.JLabel Check1;
    private javax.swing.JLabel Check10;
    private javax.swing.JLabel Check2;
    private javax.swing.JLabel Check3;
    private javax.swing.JLabel Check4;
    private javax.swing.JLabel Check5;
    private javax.swing.JLabel Check6;
    private javax.swing.JLabel Check7;
    private javax.swing.JLabel Check8;
    private javax.swing.JLabel Check9;
    private javax.swing.JLabel Edit1;
    private javax.swing.JLabel Edit10;
    private javax.swing.JLabel Edit2;
    private javax.swing.JLabel Edit3;
    private javax.swing.JLabel Edit4;
    private javax.swing.JLabel Edit5;
    private javax.swing.JLabel Edit6;
    private javax.swing.JLabel Edit7;
    private javax.swing.JLabel Edit8;
    private javax.swing.JLabel Edit9;
    private javax.swing.JLabel Falha1;
    private javax.swing.JLabel Falha10;
    private javax.swing.JLabel Falha2;
    private javax.swing.JLabel Falha3;
    private javax.swing.JLabel Falha4;
    private javax.swing.JLabel Falha5;
    private javax.swing.JLabel Falha6;
    private javax.swing.JLabel Falha7;
    private javax.swing.JLabel Falha8;
    private javax.swing.JLabel Falha9;
    private javax.swing.JTextField InserirTarefa;
    private javax.swing.JTextField Tarefa1;
    private javax.swing.JTextField Tarefa10;
    private javax.swing.JTextField Tarefa2;
    private javax.swing.JTextField Tarefa3;
    private javax.swing.JTextField Tarefa4;
    private javax.swing.JTextField Tarefa5;
    private javax.swing.JTextField Tarefa6;
    private javax.swing.JTextField Tarefa7;
    private javax.swing.JTextField Tarefa8;
    private javax.swing.JTextField Tarefa9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
